# Generated by Django 4.1.2 on 2022-10-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('Frozen', 'Frozen'), ('Resolved', 'Resolved'), ('Unresolved', 'Unresolved')], default='Frozen', max_length=10),
        ),
    ]
